### ISSUE TITLE
Git History does not forget

### ISSUE THREAD

**Issue by ModischFabrications** [mate-amargo/telegram-mc-bot#2]
Hey , you forgot to purge your token from the git history. 

https://github.com/mate-amargo/telegram-mc-bot/commit/b6f99c69e39af6bdd2a582775c81f0b2b6da5d84

Might want to change that, if I can see it others have as well.

**Comment by mate-amargo** [comment]
Thanks, really a harmless token, since after realizing I had pushed it I changed it, rendering it useless.
But nevertheless it's a good practice to purge the token from the git history.
I'll be more careful in the future :grimacing:
